# -*- coding:utf-8 -*-
{
    'name': 'BSD Kinh doanh',
    'version': 'V0.1',
    'category': 'App',
    'author': 'Thịnh Lưu',
    'depends': [
                'base',
                'mail',
                'hr',
                'bsd_du_an',
                'bsd_danh_muc',
                'base_automation',
    ],
    'data': [
        'security/user_groups.xml',
        'security/ir.model.access.csv',
        'security/bsd_security.xml',
        'views/res_partner_views.xml',
        'views/bsd_dot_mo_ban_views.xml',
        'views/bsd_product_template_views.xml',
        'views/bsd_giu_cho_thien_chi_views.xml',
        'views/bsd_rap_can_views.xml',
        'views/bsd_giu_cho_views.xml',
        'views/bsd_khuyen_mai_views.xml',
        'views/bsd_bao_gia_views.xml',
        'views/bsd_dieu_kien_ban_giao_views.xml',
        'views/bsd_dat_coc_views.xml',
        'views/bsd_menu_item_views.xml',
        'data/bsd_automation_data.xml',
        'wizards/bsd_wizard_ky_bg_views.xml',
        'wizards/bsd_wizard_ky_dc_views.xml',
        'reports/report_bsd_bao_gia_views.xml',
    ],
    'application': True,
}