# -*- coding:utf-8 -*-
{
    'name': 'BSD Kinh doanh',
    'version': 'V0.1',
    'category': 'App',
    'author': 'Thịnh Lưu',
    'depends': [
                'base',
                'mail',
                'hr',
                'bsd_du_an',
                'bsd_danh_muc',
                'base_automation',
    ],
    'data': [
        'security/user_groups.xml',
        'security/ir.model.access.csv',
        'security/bsd_security.xml',
        'views/bsd_kh_ca_nhan_views.xml',
        'views/res_partner_views.xml',
        'views/bsd_dot_mo_ban_views.xml',
        'views/bsd_product_template_views.xml',
        'views/bsd_giu_cho_thien_chi_views.xml',
        'views/bsd_rap_can_views.xml',
        'views/bsd_giu_cho_views.xml',
        'views/bsd_khuyen_mai_views.xml',
        'views/bsd_bao_gia_views.xml',
        'views/bsd_dieu_kien_ban_giao_views.xml',
        'views/bsd_dat_coc_views.xml',
        'views/bsd_chuyen_gc_views.xml',
        'views/bsd_huy_gc_views.xml',
        'views/bsd_thu_hoi_views.xml',
        'views/bsd_them_unit_views.xml',
        'views/bsd_chiet_khau_dac_biet_views.xml',
        'views/bsd_chiet_khau_chung_views.xml',
        'views/bsd_menu_item_views.xml',
        'data/bsd_automation_data.xml',
        'data/bsd_sequence_data.xml',
        'wizards/bsd_wizard_ky_bg_views.xml',
        'wizards/bsd_wizard_dc_views.xml',
        'wizards/bsd_wizard_khong_duyet_chuyen_gc_views.xml',
        'wizards/bsd_wizard_khong_duyet_thu_hoi_views.xml',
        'wizards/bsd_wizard_khong_duyet_them_unit_views.xml',
        'wizards/bsd_wizard_khong_duyet_huy_gc_views.xml',
        'wizards/bsd_wizard_khong_duyet_chiet_khau_dac_biet_views.xml',
        'reports/report_bsd_bao_gia_views.xml',
        'reports/report_bsd_dat_coc_views.xml',
    ],
    'application': True,
}