# -*- coding:utf-8 -*-
{
    'name': 'BSD Danh mục',
    'version': 'V0.1',
    'category': 'App',
    'author': 'Thịnh Lưu',
    'depends': [
                'base',
                'mail',
                'bsd_du_an',
    ],
    'data': [
        'security/user_groups.xml',
        'security/ir.model.access.csv',
        'security/bsd_security.xml',
        'data/bsd_danh_muc_data.xml',
        'views/bsd_quan_huyen_views.xml',
        'views/bsd_phuong_xa_views.xml',
        'views/bsd_lai_suat_views.xml',
        'views/bsd_dieu_kien_ban_giao_views.xml',
        'views/bsd_phuong_thuc_thanh_toan_views.xml',
        'views/bsd_phi_moi_gioi_views.xml',
        'views/bsd_tknh_ad_views.xml',
        'views/bsd_product_pricelist_views.xml',
        'views/bsd_khuyen_mai_views.xml',
        'views/bsd_chiet_khau_views.xml',
        'views/bsd_chiet_khau_chung_views.xml',
        'views/bsd_chiet_khau_mua_si_views.xml',
        'views/bsd_chiet_khau_noi_bo_views.xml',
        'views/bsd_chiet_khau_ttth_views.xml',
        'views/bsd_chiet_khau_cstt_views.xml',
        'views/bsd_chiet_khau_ttn_views.xml',
        'views/bsd_lai_phat_tt_views.xml',
        'views/bsd_chinh_sach_thanh_toan_views.xml',
        'views/bsd_ma_bo_chung_tu_views.xml',
        'views/bsd_du_an_views.xml',
        'views/bsd_thue_suat_views.xml',
        'views/bsd_menu_item_views.xml',
        'views/bsd_res_country_views.xml',
        'wizards/bsd_wizard_khong_duyet_khuyen_mai_views.xml',
        'wizards/bsd_wizard_khong_duyet_chiet_khau_views.xml',
        'wizards/bsd_wizard_khong_duyet_ck_chung_views.xml',
        'wizards/bsd_wizard_khong_duyet_ck_ms_views.xml',
        'wizards/bsd_wizard_khong_duyet_ck_nb_views.xml',
        'wizards/bsd_wizard_khong_duyet_ck_ttth_views.xml',
        'wizards/bsd_wizard_khong_duyet_ck_cstt_views.xml',
        'wizards/bsd_wizard_khong_duyet_ck_ttn_views.xml',
        'wizards/bsd_wizard_khong_duyet_cs_tt_views.xml',
        'wizards/bsd_wizard_khong_duyet_bang_gia_views.xml'
    ],
    'application': True,
}